import type {AnimStyle} from '../lib/anim';
import type {EyebrowStyle, Layout, Value} from '../lib/layouts';
import type {MotifName} from '../lib/motifs';
import type {Edge} from '../lib/paper';
import {palette, type ToneName} from '../lib/theme';

export type OverlaySpec = {
  /** Remotion composition id. */
  id: string;
  /** Output filename stem. */
  file: string;
  layout: Layout;
  eyebrow: string;
  /** Blackletter is reserved for the wordmark itself. */
  eyebrowStyle?: EyebrowStyle;
  headline: string[];
  note: string;
  value?: Value;
  motif?: MotifName;
  index?: string;
  /** `label` layout only. */
  body?: string[];
  fields?: string[];
  signature?: string;
  /** Sew a running stitch just inside the edge. */
  stitched?: boolean;
  tone: ToneName;
  accent: string;
  anim: AnimStyle;
  torn?: Edge[];
  width: number;
  height: number;
  /** Degrees the card settles at. Real paper is never square to the frame. */
  restAngle: number;
};

/**
 * Twenty overlays, in the order you'd actually hit them making a garment:
 * planning and cutting, then construction, then finishing. Each one is a real
 * instruction, not filler - the notes are the bit people screenshot.
 */
export const specs: OverlaySpec[] = [
  {
    id: 'ToileFirst',
    file: '01-toile-first',
    layout: 'instruction',
    eyebrow: 'Before the good stuff',
    headline: ['Toile it', 'in calico'],
    note: 'Never cut a print you can’t reprint.',
    motif: 'cutLine',
    tone: 'foxed',
    accent: palette.lapis,
    anim: 'slide',
    torn: ['right'],
    width: 1420,
    height: 610,
    restAngle: -0.7,
  },
  {
    id: 'Grainline',
    file: '02-grainline',
    layout: 'diagram',
    eyebrow: 'Grainline',
    headline: ['Follow the', 'selvedge'],
    note: 'Off grain and it twists on the body.',
    motif: 'grainline',
    tone: 'vellum',
    accent: palette.lapis,
    anim: 'cut',
    torn: ['bottom'],
    width: 1480,
    height: 560,
    restAngle: 0.5,
  },
  {
    id: 'CuttingFabric',
    file: '03-cutting-fabric',
    layout: 'instruction',
    eyebrow: 'Cutting',
    headline: ['Cut in a', 'single layer'],
    note: 'Printed panels shift when folded.',
    motif: 'layers',
    tone: 'vellum',
    accent: palette.sanguine,
    anim: 'cut',
    torn: ['right', 'bottom'],
    width: 1540,
    height: 610,
    restAngle: -0.4,
  },
  {
    id: 'SeamAllowance',
    file: '04-seam-allowance',
    layout: 'measure',
    eyebrow: 'Seam allowance',
    headline: ['Keep it', 'the same'],
    note: 'Every seam, or nothing lines up.',
    value: {num: '1', den: '4', unit: '″'},
    tone: 'vellum',
    accent: palette.bole,
    anim: 'stamp',
    torn: ['right'],
    width: 1420,
    height: 500,
    restAngle: -1.1,
  },
  {
    id: 'RightSidesTogether',
    file: '05-right-sides-together',
    layout: 'tag',
    eyebrow: 'Before you sew',
    headline: ['Right sides', 'together'],
    note: 'Print faces print.',
    index: 'RST',
    tone: 'parchment',
    accent: palette.bole,
    anim: 'slide',
    torn: ['right'],
    width: 1220,
    height: 560,
    restAngle: 0.9,
  },
  {
    id: 'BasteFirst',
    file: '06-baste-first',
    layout: 'tag',
    eyebrow: 'Trial run',
    headline: ['Baste it', 'first'],
    note: 'Longest stitch. No backstitch.',
    index: '01',
    tone: 'parchment',
    accent: palette.lapis,
    anim: 'drop',
    torn: ['bottom'],
    width: 1180,
    height: 560,
    restAngle: -0.8,
  },
  {
    id: 'JerseyNeedle',
    file: '07-jersey-needle',
    layout: 'instruction',
    eyebrow: 'Needles',
    headline: ['Ballpoint', 'for jersey'],
    note: 'A sharp splits the knit. It ladders.',
    motif: 'registration',
    tone: 'nocturne',
    accent: palette.gilt,
    anim: 'stamp',
    torn: ['right'],
    width: 1420,
    height: 610,
    restAngle: 0.6,
  },
  {
    id: 'Backstitch',
    file: '08-backstitch',
    layout: 'instruction',
    eyebrow: 'Lock it off',
    headline: ['Backstitch', 'both ends'],
    note: 'Three forward, three back.',
    motif: 'stitchRows',
    tone: 'vellum',
    accent: palette.verdigris,
    anim: 'drop',
    torn: ['right'],
    width: 1400,
    height: 610,
    restAngle: -0.5,
  },
  {
    id: 'Staystitch',
    file: '09-staystitch',
    layout: 'measure',
    eyebrow: 'Staystitch',
    headline: ['From the', 'raw edge'],
    note: 'Single layer. Stops it stretching.',
    value: {num: '1', den: '2', unit: '″'},
    tone: 'vellum',
    accent: palette.verdigris,
    anim: 'stamp',
    torn: ['bottom'],
    width: 1460,
    height: 500,
    restAngle: 0.8,
  },
  {
    id: 'ClipTheCurves',
    file: '10-clip-the-curves',
    layout: 'diagram',
    eyebrow: 'Curves',
    headline: ['Clip in,', 'notch out'],
    note: 'Clip concave. Notch convex.',
    motif: 'notch',
    tone: 'vellum',
    accent: palette.sanguine,
    anim: 'cut',
    torn: ['right'],
    width: 1300,
    height: 560,
    restAngle: -0.6,
  },
  {
    id: 'EaseTheSleeve',
    file: '11-ease-the-sleeve',
    layout: 'diagram',
    eyebrow: 'Sleeve head',
    headline: ['Ease it,', 'don’t gather'],
    note: 'The cap is longer than the armhole.',
    motif: 'ease',
    tone: 'foxed',
    accent: palette.lapis,
    anim: 'drop',
    torn: ['bottom'],
    width: 1440,
    height: 560,
    restAngle: 0.4,
  },
  {
    id: 'Interfacing',
    file: '12-interfacing',
    layout: 'instruction',
    eyebrow: 'Interfacing',
    headline: ['Bumpy side', 'down'],
    note: 'Glue side down. Press, don’t slide.',
    motif: 'pressArrow',
    tone: 'vellum',
    accent: palette.bole,
    anim: 'cut',
    torn: ['right'],
    width: 1400,
    height: 610,
    restAngle: -0.9,
  },
  {
    id: 'PressSeamsOpen',
    file: '13-press-seams-open',
    layout: 'instruction',
    eyebrow: 'The press',
    headline: ['Press seams', 'open'],
    note: 'Lift and lower. Never drag the iron.',
    motif: 'seamOpen',
    tone: 'vellum',
    accent: palette.sanguine,
    anim: 'unfold',
    torn: ['right'],
    width: 1460,
    height: 610,
    restAngle: 0.7,
  },
  {
    id: 'Topstitch',
    file: '14-topstitch',
    layout: 'measure',
    eyebrow: 'Topstitch',
    headline: ['From the', 'seam'],
    note: 'Stitch length 3.0. Go slow.',
    value: {num: '1', den: '8', unit: '″'},
    tone: 'foxed',
    accent: palette.bole,
    anim: 'slide',
    torn: ['right'],
    width: 1320,
    height: 500,
    restAngle: -0.4,
  },
  {
    id: 'BarTack',
    file: '15-bar-tack',
    layout: 'diagram',
    eyebrow: 'Stress points',
    headline: ['Bar tack it'],
    note: 'Pocket corners. Belt loops. Vents.',
    motif: 'barTack',
    tone: 'nocturne',
    accent: palette.gilt,
    anim: 'stamp',
    torn: ['right'],
    width: 1420,
    height: 480,
    restAngle: 0.9,
  },
  {
    id: 'FinishTheEdge',
    file: '16-finish-the-edge',
    layout: 'diagram',
    eyebrow: 'Raw edges',
    headline: ['Overlock', 'or zigzag'],
    note: 'No serger? A zigzag holds it.',
    motif: 'zigzag',
    tone: 'vellum',
    accent: palette.verdigris,
    anim: 'slide',
    torn: ['bottom'],
    width: 1340,
    height: 560,
    restAngle: -0.7,
  },
  {
    id: 'BiasBinding',
    file: '17-bias-binding',
    layout: 'diagram',
    eyebrow: 'Bias',
    headline: ['Cut at 45°'],
    note: 'Only bias stretches round a curve.',
    motif: 'bias',
    tone: 'vellum',
    accent: palette.sanguine,
    anim: 'cut',
    torn: ['right'],
    width: 1420,
    height: 480,
    restAngle: 0.5,
  },
  {
    id: 'DoubleFoldHem',
    file: '18-double-fold-hem',
    layout: 'diagram',
    eyebrow: 'Hem',
    headline: ['Turn it twice'],
    note: 'Encloses the raw edge. No fraying.',
    motif: 'doubleFold',
    tone: 'foxed',
    accent: palette.bole,
    anim: 'unfold',
    torn: ['bottom'],
    width: 1500,
    height: 480,
    restAngle: -0.5,
  },
  {
    id: 'Unpick',
    file: '19-unpick',
    layout: 'tag',
    eyebrow: 'When it goes wrong',
    headline: ['Unpick it'],
    note: 'Measure twice. Unpick once.',
    index: '00',
    tone: 'parchment',
    accent: palette.sanguine,
    anim: 'drop',
    torn: ['right'],
    width: 1120,
    height: 470,
    restAngle: 1.1,
  },
  {
    id: 'LeaveItRaw',
    file: '20-leave-it-raw',
    layout: 'instruction',
    eyebrow: 'Roughcut',
    eyebrowStyle: 'gothic',
    headline: ['Leave the', 'seam raw'],
    note: 'It’s meant to fray. That’s the point.',
    motif: 'fray',
    tone: 'oxblood',
    accent: palette.gilt,
    anim: 'cut',
    torn: ['right', 'bottom'],
    width: 1440,
    height: 610,
    restAngle: -1,
  },
  {
    id: 'RelicLabel',
    file: '21-relic-label',
    layout: 'label',
    eyebrow: 'Certificate of authentication',
    headline: ['Relic from the past', 'crafted in the present'],
    note: '',
    body: [
      'Designed, cut and sewn by hand in the',
      'south of England. Inspired by the ruins,',
      'the paintings and the archaeology.',
      'No two will ever be the same.',
    ],
    fields: ['Garment No.', 'Final stitching.'],
    signature: 'RoughCut',
    stitched: true,
    tone: 'parchment',
    accent: palette.bole,
    anim: 'unfold',
    torn: ['right', 'bottom'],
    width: 1320,
    height: 940,
    restAngle: -0.6,
  },
  {
    id: 'PatchSheets',
    file: '22-patch-sheets',
    layout: 'tag',
    eyebrow: 'From the archive',
    headline: ['Patch sheets'],
    note: 'The ones I use. Link in the description.',
    index: 'RC',
    stitched: true,
    tone: 'foxed',
    accent: palette.sanguine,
    anim: 'drop',
    torn: ['right'],
    width: 1240,
    height: 470,
    restAngle: 0.9,
  },
];
