#!/usr/bin/env python3
"""
Extracts the digit outlines from Nimbus Sans Bold and bakes them into
`src/chapters/glyphs.ts` as flattened contours.

    python3 scripts/extract-digits.py

WHY BAKE THEM. The stitch animation sews along the numeral's outline, so it
needs that outline as geometry rather than as a rendered glyph. The obvious
route — draw the number as SVG text, then walk it with getPointAtLength — does
not work here: the outline of a <text> element is not exposed to script, and
anything that measures the DOM during a render is asynchronous and therefore
not deterministic frame to frame. Remotion renders each frame independently, so
a stitch whose position depends on a measurement is a stitch that can move
between two renders of the same frame.

Baking removes the problem entirely. The contours are flattened here, once, at
a resolution fine enough that the error is invisible, and the component does
nothing at render time but walk a fixed array.

The contours are emitted in FONT UNITS (per em), not pixels, because the same
digits are sewn at 158px on a chapter card and could be sewn at 32px on the
contents card. Arc-length resampling to a pixel stitch pitch happens at render
time against the scaled polyline, which is a few hundred cheap sums.

Winding matters: a glyph's outer contour and its counter (the hole in 0, 6, 8,
9) run in opposite directions. That is preserved, because the needle should
travel around the counter the way the outline actually runs.
"""
import json
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import DecomposingRecordingPen

FONT = '/usr/share/fonts/opentype/urw-base35/NimbusSans-Bold.otf'
OUT = 'src/chapters/glyphs.ts'

#

# Flattening resolution. A cubic is split into this many segments; at 158px a
# digit is ~110px tall, so 24 segments per curve puts the chord error far below
# a tenth of a pixel.
STEPS = 24


def bez3(p0, p1, p2, p3, steps=STEPS):
    out = []
    for i in range(1, steps + 1):
        t = i / steps
        u = 1 - t
        out.append((
            u * u * u * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t * t * t * p3[0],
            u * u * u * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t * t * t * p3[1],
        ))
    return out


def bez2(p0, p1, p2, steps=STEPS):
    out = []
    for i in range(1, steps + 1):
        t = i / steps
        u = 1 - t
        out.append((
            u * u * p0[0] + 2 * u * t * p1[0] + t * t * p2[0],
            u * u * p0[1] + 2 * u * t * p1[1] + t * t * p2[1],
        ))
    return out


def contours_for(font, glyph_set, name):
    pen = DecomposingRecordingPen(glyph_set)
    glyph_set[name].draw(pen)
    contours, cur, start = [], [], None
    for op, args in pen.value:
        if op == 'moveTo':
            if cur:
                contours.append(cur)
            start = args[0]
            cur = [start]
        elif op == 'lineTo':
            cur.append(args[0])
        elif op == 'curveTo':
            cur.extend(bez3(cur[-1], args[0], args[1], args[2]))
        elif op == 'qCurveTo':
            # qCurveTo can carry several off-curve points with implied on-curve
            # midpoints between them; the last argument is the real endpoint.
            pts = list(args)
            end = pts.pop()
            prev = cur[-1]
            for i, c in enumerate(pts):
                nxt = end if i == len(pts) - 1 else (
                    (c[0] + pts[i + 1][0]) / 2, (c[1] + pts[i + 1][1]) / 2
                )
                cur.extend(bez2(prev, c, nxt))
                prev = nxt
        elif op == 'closePath':
            if cur and cur[0] != cur[-1]:
                cur.append(cur[0])
            contours.append(cur)
            cur = []
    if cur:
        contours.append(cur)
    return contours


def area(c):
    """Signed area; the sign is the winding direction."""
    s = 0.0
    for i in range(len(c) - 1):
        s += c[i][0] * c[i + 1][1] - c[i + 1][0] * c[i][1]
    return s / 2


def main():
    font = TTFont(FONT)
    upem = font['head'].unitsPerEm
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font['hmtx']

    data = {}
    for d in '0123456789':
        name = cmap[ord(d)]
        cs = contours_for(font, gs, name)
        # Outer contour first — the one the needle starts on — then counters,
        # largest first. |area| ranks them without assuming a winding rule.
        cs.sort(key=lambda c: -abs(area(c)))
        data[d] = {
            'advance': hmtx[name][0],
            'contours': [[[round(x, 1), round(y, 1)] for x, y in c] for c in cs],
        }
        print(f"  {d}: {len(cs)} contour(s), "
              f"{sum(len(c) for c in cs)} points, advance {hmtx[name][0]}")

    with open(OUT, 'w') as f:
        f.write('/**\n')
        f.write(' * GENERATED by scripts/extract-digits.py — do not edit by hand.\n')
        f.write(' *\n')
        f.write(' * Digit outlines from Nimbus Sans Bold, flattened to polylines in font\n')
        f.write(' * units. Y is in FONT space (up is positive), so the consumer flips it.\n')
        f.write(' * Contours are ordered outer-first, then counters largest-first: that is\n')
        f.write(' * the order the needle sews them in.\n')
        f.write(' *\n')
        f.write(f' * unitsPerEm {upem}\n')
        f.write(' */\n')
        f.write(f'export const UPEM = {upem};\n\n')
        f.write('export type Glyph = {advance: number; contours: number[][][]};\n\n')
        f.write('export const DIGITS: Record<string, Glyph> = ')
        f.write(json.dumps(data, separators=(',', ':')))
        f.write(';\n')
    print(f"\nwrote {OUT}")


if __name__ == '__main__':
    main()
