#!/usr/bin/env python3
"""
Bakes QR codes into `src/banners/qr.ts` as module matrices.

    python3 scripts/make-qr.py dm=https://wa.me/44... group=https://chat.whatsapp.com/...

WHY GENERATE RATHER THAN TRACE A SCREENSHOT. A QR lifted from a picture has to
be resampled to land on the banner, and a resampled QR is a QR with soft module
edges — which is the thing scanners are worst at. Generated from the URL it is
an exact matrix, so it can be drawn as crisp rectangles at any size, recoloured
to suit the design, and given a real quiet zone. It also means the payload is
verifiable, which a traced one is not.

Every code written here is DECODED BACK with OpenCV before it is emitted. A QR
that points somewhere unintended is worse than no QR at all, and a silent
mis-encode is exactly the kind of failure nobody notices until it is printed on
a two-hour video.

ERROR CORRECTION IS M, NOT H, AND THAT IS THE OPPOSITE OF THE OBVIOUS CHOICE.

Higher correction sounds safer and is worse here. It buys redundancy by adding
modules, and more modules inside a fixed patch means SMALLER ones — which is
exactly what kills a code being scanned off a screen. Measured on a realistic
community-invite URL, rendered at 260px and then halved as if someone were
watching in a small window:

    ecc M  260px -> 130px   READS
    ecc Q  260px -> 130px   fails
    ecc H  260px -> 130px   fails

M at 260px is the only combination that survives, so that is what is used. The
codes are on a clean cream patch with nothing overlapping them, which is the
case high correction exists for and this is not.
"""
import sys

import cv2
import numpy as np
import segno

OUT = 'src/banners/qr.ts'


def matrix(url: str):
    q = segno.make(url, error='m')
    m = [[1 if c else 0 for c in row] for row in q.matrix]
    return m, q.version


def verify(m, url: str) -> bool:
    """Render big, then read it back. Nothing is emitted that fails this."""
    n = len(m)
    scale, quiet = 10, 4
    size = (n + quiet * 2) * scale
    img = np.full((size, size), 255, np.uint8)
    for y in range(n):
        for x in range(n):
            if m[y][x]:
                y0 = (y + quiet) * scale
                x0 = (x + quiet) * scale
                img[y0:y0 + scale, x0:x0 + scale] = 0
    got, _, _ = cv2.QRCodeDetector().detectAndDecode(img)
    if got != url:
        print(f'   VERIFY FAILED: decoded {got!r}, expected {url!r}')
        return False
    return True


def main():
    args = [a for a in sys.argv[1:] if '=' in a]
    if not args:
        sys.exit('usage: make-qr.py name=URL [name=URL ...]')

    out = {}
    for a in args:
        name, url = a.split('=', 1)
        m, ver = matrix(url)
        ok = verify(m, url)
        print(f'  {name}: version {ver}, {len(m)}x{len(m)} modules, '
              f'{"decoded OK" if ok else "FAILED"}  <- {url}')
        if not ok:
            sys.exit('refusing to emit a QR that does not decode back to its URL')
        out[name] = (url, m)

    with open(OUT, 'w') as f:
        f.write('/**\n')
        f.write(' * GENERATED by scripts/make-qr.py — do not edit by hand.\n')
        f.write(' *\n')
        f.write(' * QR module matrices, error correction level M — see make-qr.py for why\n')
        f.write(' * that beats H here. Each was decoded back\n')
        f.write(' * with OpenCV before being written here, so the payload below is what a\n')
        f.write(' * phone will actually read.\n')
        f.write(' *\n')
        f.write(' * 1 is a dark module. Draw dark-on-light and keep the quiet zone.\n')
        f.write(' */\n')
        f.write('export type Qr = {url: string; modules: number[][]};\n\n')
        for name, (url, m) in out.items():
            rows = ','.join('[' + ','.join(str(v) for v in r) + ']' for r in m)
            f.write(f'/** {url} */\n')
            f.write(f'export const {name.upper()}: Qr = {{url: {url!r}, modules: [{rows}]}};\n\n')
    print(f'\nwrote {OUT}')


if __name__ == '__main__':
    main()
